### ISSUE TITLE
'grid' is undefined

### ISSUE THREAD

**Issue by saschanaz** [codler/Grid-Layout-Polyfill#4]
I just cannot call $(grid).gridLayout('refresh') because 'grid' is undefined.
http://jsfiddle.net/saschanaz/KvjhX/1/

How can I call it, or is there other way to do it?

**Comment by codler** [comment]
'grid' is a variable you should define, which is a selector on a grid. See the tests for example how to use them.

**Comment by saschanaz** [comment]
@codler Oh, I didn't know there are many tests! Thank you :D
